//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.Win
{
    using System;
    using System.Collections.Generic;
    
    public partial class meetingTBL
    {
        public int Id { get; set; }
        public int projectID { get; set; }
        public int typeID { get; set; }
        public string address { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan duration { get; set; }
        public string notes { get; set; }
    
        public virtual meetingTypeTBL meetingTypeTBL { get; set; }
        public virtual projectTBL projectTBL { get; set; }
    }
}
