//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.Win
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<costumerTBL> costumerTBL { get; set; }
        public virtual DbSet<lecturesNseminarsTBL> lecturesNseminarsTBL { get; set; }
        public virtual DbSet<meetingTBL> meetingTBL { get; set; }
        public virtual DbSet<meetingTypeTBL> meetingTypeTBL { get; set; }
        public virtual DbSet<orderTBL> orderTBL { get; set; }
        public virtual DbSet<projectTBL> projectTBL { get; set; }
        public virtual DbSet<serviceTBL> serviceTBL { get; set; }
        public virtual DbSet<subOrderTBL> subOrderTBL { get; set; }
        public virtual DbSet<orderHistoryView> orderHistoryView { get; set; }
        public virtual DbSet<SubOrderView> SubOrderView { get; set; }
    }
}
