//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.Win
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orderTBL()
        {
            this.subOrderTBL = new HashSet<subOrderTBL>();
        }
    
        public int Id { get; set; }
        public int costumerID { get; set; }
        public string address { get; set; }
        public System.DateTime date { get; set; }
        public string notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subOrderTBL> subOrderTBL { get; set; }
        public virtual costumerTBL costumerTBL { get; set; }
    }
}
