//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.Win
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderHistoryView
    {
        public int Id { get; set; }
        public System.DateTime orderDate { get; set; }
        public string orderNotes { get; set; }
        public string adress { get; set; }
        public int amountInvited { get; set; }
        public System.DateTime date { get; set; }
        public int orderID { get; set; }
        public string subOrderNotes { get; set; }
        public int lectureID { get; set; }
        public string fullName { get; set; }
        public string title { get; set; }
    }
}
