//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.Win
{
    using System;
    using System.Collections.Generic;
    
    public partial class projectTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public projectTBL()
        {
            this.meetingTBL = new HashSet<meetingTBL>();
        }
    
        public int Id { get; set; }
        public int customerID { get; set; }
        public string title { get; set; }
        public int serviceID { get; set; }
        public bool inProcess { get; set; }
        public string description { get; set; }
        public System.DateTime creationDate { get; set; }
    
        public virtual costumerTBL costumerTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meetingTBL> meetingTBL { get; set; }
        public virtual serviceTBL serviceTBL { get; set; }
    }
}
