//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landau.Win
{
    using System;
    using System.Collections.Generic;
    
    public partial class projectTrackView
    {
        public int meetingID { get; set; }
        public System.TimeSpan duration { get; set; }
        public int projectID { get; set; }
        public int typeID { get; set; }
        public string address { get; set; }
        public System.DateTime date { get; set; }
        public string notes { get; set; }
        public string topic { get; set; }
        public string name { get; set; }
        public int customerID { get; set; }
        public int serviceID { get; set; }
        public string title { get; set; }
        public string serviceName { get; set; }
        public string fullName { get; set; }
    }
}
